services:
  manager.blog.post:
    class: AppBundle\Manager\BlogPostManager
    arguments: ['@repository.blog.post']

  repository.blog.post:
    class: AppBundle\Entity\Repository\BlogPostRepository
    factory: ["@doctrine", getRepository]
    arguments: [AppBundle:BlogPost]

  facebook:
    class: AppBundle\Services\PublishOnFacebook


  twitter:
    class: AppBundle\Services\PublishOnTwitter

  publisher:
    class: AppBundle\Services\BlogPostPublisher
    arguments: ['@service_container', !tagged onPublishPost]

  service.send.Notification:
      class: AppBundle\Services\SendNotification
      tags: ['onPublishPost']

