services:
  manager.blog.post:
    class: AppBundle\Manager\BlogPostManager
    arguments: ['@repository.blog.post']

  repository.blog.post:
    class: AppBundle\Entity\Repository\BlogPostRepository
    factory: ["@doctrine", getRepository]
    arguments: [AppBundle:BlogPost]


  factory:
    class: AppBundle\Factory\PublisherFactory
    arguments: [!tagged onPublishPost]
    share: false

  facebook:
    class: AppBundle\Factory\PublisherFactory
    factory: ['@factory', createPublisher]
    arguments: [AppBundle\Services\PublishOnFacebook]

  twitter:
    class: AppBundle\Factory\PublisherFactory
    factory: ['@factory', createPublisher]
    arguments: [AppBundle\Services\PublishOnTwitter]

  service.send.Notification:
      class: AppBundle\Services\SendNotification
      tags: ['onPublishPost']

